[tool.cibuildwheel]
build = ["cp310-*",]
#before-all = "bash {project}/scripts/build_pmix.sh 2>&1 | tee /tmp/pmix-build.log && echo 'BUILD DONE' && ls /tmp/pmix/lib/ || echo 'BUILD FAILED'"
build-frontend = "build"
skip = "*-musllinux*"

[tool.cibuildwheel.linux]
environment = { PMIX_PREFIX = "/opt/pmix", PKG_CONFIG_PATH = "/opt/pmix/lib/pkgconfig", LD_LIBRARY_PATH = "/opt/pmix/lib", LIBRARY_PATH = "/opt/pmix/lib", C_INCLUDE_PATH = "/opt/pmix/include", CFLAGS = "-I/opt/pmix/include", LDFLAGS = "-L/opt/pmix/lib -Wl,-rpath,/opt/pmix/lib" }
repair-wheel-command = "LD_LIBRARY_PATH=/tmp/pmix/lib auditwheel repair -w {dest_dir} {wheel}"
manylinux-aarch64-image = "ghcr.io/wesenheit/manylinux-pmix:5.0.9-aarch64"
manylinux-x86_64-image = "ghcr.io/wesenheit/manylinux-pmix:5.0.9-x86_64"
