[workspace]
name = "rixa"
channels = ["nvidia","pytorch","conda-forge"]
platforms = ["linux-64", "osx-arm64"]
channel-priority = "disabled"
preview = ["pixi-build"]

[dependencies]
python = "3.12.*"
openmpi = ">=5.0"
libpmix = ">=5.0"
patchelf = ">=0.17.2,<0.19"
cibuildwheel = ">=3.4.1,<4"
pytest = ">=9.0.3,<10"
pip = ">=26.1.1,<27"
setuptools = ">=82.0.1,<83"
numpy = ">2.0.0"
ninja = ">=1.13.2,<2"
setuptools-scm = ">=10.2.0,<11"

[pypi-dependencies]
rixa = { path = ".", editable = true }
build = ">=1.5.0, <2"
twine = ">=6.2.0, <7"
auditwheel = ">=6.6.0, <7"
sphinx = ">=9.1.0, <10"
sphinx-rtd-theme = ">=3.1.0, <4"
myst-parser = ">=5.1.0, <6"
torch = ">=2.8.0"

[feature.gpu]
channels = ["pytorch", "nvidia", "conda-forge"]
platforms = ["linux-64"]

[feature.gpu.dependencies]
cuda-python = ">=12.0"
nvshmem4py = ">0.3.0"

[feature.cpu]
channels = ["conda-forge"]
platforms = ["osx-arm64","linux-64"]


[environments]
linux-gpu = { features = ["gpu"], solve-group = "gpu-group" }
default = { features = ["cpu"], solve-group = "cpu-group" }


[package]
name = "rixa"
version = "0.0.4"

[package.build]
backend = { name = "pixi-build-python", version = "*" }


[package.build.config]
noarch = false
abi3 = true
compilers = ["c",]

[package.host-dependencies]
libpmix = ">=5.0"
setuptools = "*"
pytorch = ">=2.8.0"
pybind11 = "*"

[tasks]
build = "pip install --no-build-isolation -e ."
test = "pytest tests -v"
test-cpu = "pytest tests -v -m cpu"
ci = { depends-on = ["build", "test"] }
ci-cpu = { depends-on = ["build", "test-cpu"] }

## CLEAN AND TEST OBJECTS
clean = "rm -rf dist/ wheelhouse/ build/"
check-wheel = "twine check wheelhouse/* "
check-dist = "twine check dist/* "
sdist= "python -m build --sdist"

### TESTING BUILD
wheel-test = "python -m build --wheel"
audit-test = "auditwheel repair dist/*.whl -w wheelhouse/"
pre-publish-test = { depends-on = ["clean","wheel-test","sdist", "audit-test","check-wheel","check-dist"]}

## PRODUCTION BUILD
build-wheelhouse = "cibuildwheel --config-file cibuildwheel.toml --platform linux --archs aarch64,x86_64"
pre-publish = { depends-on = ["clean", "build-wheelhouse", "sdist","check-wheel","check-dist"]}

## PUBLISH
publish-test = "twine upload --repository testpypi wheelhouse/* --verbose"
publish = "twine upload --repository pypi wheelhouse/*"

publish-source-test = "twine upload --repository testpypi dist/*.tar.gz"
publish-source = "twine upload --repository pypi dist/*.tar.gz"

full-publish-test = {depends-on = ["publish-test", "publish-source-test"]}
full-publish = {depends-on = ["publish", "publish-source"]}


#docker
docker-build = "bash scripts/build_docker.sh"
docker-publish = "docker push ghcr.io/wesenheit/manylinux-pmix:5.0.9-aarch64 && docker push ghcr.io/wesenheit/manylinux-pmix:5.0.9-x86_64"


#apptainer
apptainer-build = "apptainer build rixa_25.06_5.0.9.sif scripts/apptainer/pytorch.def"
