[project]
name = "rixa"
version = "0.0.4.dev0"
description = "PMIx bootstrap method for modern AI/ML applications"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

authors = [
    {name = "Mateusz Kapusta", email = "mr.kapusta@student.uw.edu.pl"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: System :: Distributed Computing",
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
]

keywords = ["PMIx", "HPC", "distributed-computing", "machine-learning", "slurm"]

[project.optional-dependencies]
torch = ["torch>=2.8.0","numpy>=1.26","ninja"]
nvshmem = ["nvshmem4py","numpy>=1.26"]

[build-system]
requires = [
    "setuptools>=61.0",
     "wheel",
    "pybind11",
]
build-backend = "setuptools.build_meta"

[tool.ruff]
target-version = "py310"
line-length = 88
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
]

[tool.ruff.lint]
select = ["E", "F", "I", "B"]
ignore = []
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
