from typing import Sequence

class PMIxStore:
    def __init__(self, timeout: int) -> None: ...
    def get_rank(self) -> int: ...
    def get_local_rank(self) -> int: ...
    def get_world(self) -> int: ...
    def set(self, key: str | bytes, value: str | bytes) -> None: ...
    def get(self, key: str | bytes) -> bytes: ...
    def wait(self, keys: Sequence[str | bytes], timeout: int = -1) -> None: ...
    def broadcastset(
        self, key: str | bytes, value: str | bytes, root: int
    ) -> bytes: ...
